import BootstrapJs from "./Bootstrap";
import HeaderMenuContextProvider from "./context/header-menu-context/HeaderMenuContextProvider";
import Header from "./components/header/Header";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.min.css";
import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <HeaderMenuContextProvider>
      <html lang="en">
        <body>
          <Header/>
          {children}
          <BootstrapJs/>
        </body>
      </html>
    </HeaderMenuContextProvider>
  );
}
